const money = n => `₹${Math.round((n ?? 0) / 100).toLocaleString('en-IN')}`;
const escapeHtml = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmtDate = d => new Intl.DateTimeFormat('en-IN',{timeZone:'Asia/Kolkata',day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${d}T12:00:00+05:30`));
const fmtTime = d => new Intl.DateTimeFormat('en-IN',{timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit',hour12:true}).format(new Date(d));
async function load(){
  const [reports,audits,plan]=await Promise.all(['data/reports/index.json','data/audits/index.json','data/portfolio.json'].map(p=>fetch(p).then(r=>r.json())));
  const latest=[...reports].reverse().find(r=>r.status==='PUBLISHED');
  const latestReport=reports.at(-1); const audit=latestReport?audits[latestReport.date]:null;
  const d=new Date();document.querySelector('#journal-date').textContent=new Intl.DateTimeFormat('en-IN',{timeZone:'Asia/Kolkata',weekday:'short',day:'2-digit',month:'short',year:'numeric'}).format(d);
  const last=latest?fmtDate(latest.date)+' · '+fmtTime(latest.generatedAt)+' IST':'Not yet refreshed';document.querySelector('#refresh-label').textContent=latest?`Last refresh ${fmtTime(latest.generatedAt)} IST`:'No successful refresh';document.querySelector('#footer-refresh').textContent=last;
  document.querySelector('#market-status').textContent=latestReport?.status==='MARKET_CLOSED'?'Market closed':latest?'Data refreshed':'Data unavailable';
  document.querySelector('#data-state').textContent=latest?'Connected':'Unavailable';document.querySelector('#data-note').textContent=latest?`Data as of ${fmtTime(latest.dataAsOf)} IST`:(latestReport?.unavailableReason||'Connect a trusted provider to refresh.');
  const deployed=plan.deployedCents??0,cash=(plan.capitalCents??0)-deployed;['#deployed','#plan-deployed'].forEach(id=>document.querySelector(id).innerHTML=id==='#plan-deployed'?`${money(deployed)} <small>/ ${money(plan.capitalCents)}</small>`:money(deployed));document.querySelector('#cash').textContent=money(cash);document.querySelector('#plan-cash').textContent=money(cash);
  const sectors=latest?.sectors??[];document.querySelector('#sectors').innerHTML=sectors.length?sectors.map(x=>`<div class="watch-row"><strong>${escapeHtml(x.name)}</strong><span>${escapeHtml(x.note||'In review')}</span></div>`).join(''):['Banks & financials','Consumer','Industrials','Healthcare'].map(x=>`<div class="watch-row"><strong>${x}</strong><span>Watchlist · no live data</span></div>`).join('');
  const tracking=latest?.tracking??[];const base=tracking.length?tracking: [{name:'Gold',kind:'Commodity',value:'Awaiting data'},{name:'Silver',kind:'Commodity',value:'Awaiting data'},{name:'Nifty ETF',kind:'ETF',value:'Awaiting data'},{name:'Gold ETF',kind:'ETF',value:'Awaiting data'}];document.querySelector('#tracking').innerHTML=base.map(x=>`<div class="tracking-cell"><span>${escapeHtml(x.kind||'TRACKING')} · ${escapeHtml(x.name)}</span><strong>${escapeHtml(x.value??'Awaiting data')}</strong></div>`).join('');
  const points=latest?.metrics?.history?.filter(p=>Number.isFinite(p.value))??[];
  if(points.length>1){const lo=Math.min(...points.map(p=>p.value)),hi=Math.max(...points.map(p=>p.value)),span=hi-lo||1;const path=points.map((p,i)=>`${i?'L':'M'} ${(i*500/(points.length-1)).toFixed(1)} ${(88-(p.value-lo)*76/span).toFixed(1)}`).join(' ');document.querySelector('#market-chart').innerHTML=`<path d="${path}"/>`;document.querySelector('#chart-empty').hidden=true;document.querySelector('.empty-note').textContent=`Nifty 50 · provider-sourced history · ${points.length} observations`;}
  const close=[...reports].reverse().find(r=>r.type==='closing');const closeAudits=close?audits[close.date]:null;const closeAudit=Array.isArray(closeAudits)?closeAudits.at(-1):closeAudits;document.querySelector('#latest-close').innerHTML=close?`<strong>${escapeHtml(fmtDate(close.date))} · ${escapeHtml(close.status)}</strong><br>${escapeHtml(close.summary)}<br><span>Audit: ${escapeHtml(closeAudit?.status||'PENDING')}</span>`:'No closing report recorded yet.<br><span>Scheduled reports appear here after the first refresh.</span>';
  const months=['Oct','Nov','Dec','Jan','Feb','Mar','Apr','May','Jun','Jul'];const localNow=new Date(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit'}).format(new Date())+'-01T00:00:00');const monthIndex=(localNow.getFullYear()-2026)*12+localNow.getMonth()-9;document.querySelector('#tranche-grid').innerHTML=months.map((m,i)=>`<div class="tranche ${i===monthIndex?'current':''}" title="${i+1}: ${m} ${i<3?'2026':'2027'}">${m}</div>`).join('');
  const list=document.querySelector('#archive-list'),query=document.querySelector('#search'),filter=document.querySelector('#report-filter');
  function draw(){const q=query.value.toLowerCase(),f=filter.value;const groups=[...new Set(reports.map(r=>r.date))].sort().reverse().map(date=>({date,items:reports.filter(r=>r.date===date)})).map(g=>({...g,items:g.items.filter(r=>(f==='all'||r.type===f)&&(!q||`${r.summary} ${r.status} ${r.type} ${r.unavailableReason||''}`.toLowerCase().includes(q)))})).filter(g=>g.items.length);
    document.querySelector('#record-count').textContent=`${reports.length} record${reports.length===1?'':'s'}`;
    list.innerHTML=groups.length?groups.map(g=>{const all=audits[g.date];const a=(Array.isArray(all)?all.at(-1):all)||{status:'WARN',findings:[{message:'Audit pending.'}]};return `<article class="archive-day"><div class="day-head"><strong>${escapeHtml(fmtDate(g.date))}</strong><span class="audit ${escapeHtml(a.status)}">${escapeHtml(a.status)} · ${a.findings.length} checks</span></div>${g.items.map(r=>`<div class="report-row"><span class="report-time">${escapeHtml(fmtTime(r.generatedAt))} IST</span><div class="report-copy"><strong>${escapeHtml(r.type==='opening'?'Opening review':r.type==='closing'?'Closing review':r.type==='correction'?'Correction note':'Market closed')} · ${escapeHtml(r.status)}</strong><p>${escapeHtml(r.summary)}</p></div><span class="report-label">${escapeHtml(r.type.toUpperCase())}</span><details><summary>Report &amp; audit details</summary><ul><li>Generated: ${escapeHtml(r.generatedAtIST||r.generatedAt)}</li><li>Data as of: ${escapeHtml(r.dataAsOf||'Unavailable')}</li>${(r.sources||[]).map(s=>`<li>Source: <a href="${escapeHtml(s.url)}" target="_blank" rel="noopener">${escapeHtml(s.name)}</a></li>`).join('')}${(r.actionLog||[]).map(x=>`<li>Action: ${escapeHtml(x.kind)} ${escapeHtml(money(x.amountCents))} · ${escapeHtml(x.note||'')}</li>`).join('')}${(r.corrections||[]).map(x=>`<li>Correction: ${escapeHtml(x.reason)} · <a href="${escapeHtml(x.sourceUrl)}" target="_blank" rel="noopener">source</a></li>`).join('')}${(a.findings||[]).map(x=>`<li>${escapeHtml(x.level)} · ${escapeHtml(x.message)}</li>`).join('')}${r.unavailableReason?`<li>${escapeHtml(r.unavailableReason)}</li>`:''}</ul></details></div>`).join('')}</article>`}).join(''):'<div class="archive-empty">No matching journal entries.</div>';
  }
  query.addEventListener('input',draw);filter.addEventListener('change',draw);draw();
}
load().catch(()=>{document.querySelector('#data-note').textContent='Journal data could not be loaded.';});
